use_frameworks!

platform :ios, '8.0'

target 'MJContactsManager_Example' do
  pod 'MJContactsManager', :path => '../'

  target 'MJContactsManager_Tests' do
    inherit! :search_paths

    
  end
end
